### ISSUE TITLE
make STORM working

### ISSUE THREAD

**Issue by xhajnal** [xhajnal/mpm#15]
If not
- [x] consider intervals in python -- see email from @tatjanapetrov -- intervals and lifting
- [x] heuristical sampling as Storm does -- see #21 #22 and fae9a6afc52d98a8695d5140c05b8b093a284837 and following commits

**Comment by tatjanapetrov** [comment]
Does the server with larger memory help?

**Comment by xhajnal** [comment]
> Does the server with larger memory help?

I was unlucky running it, since the first time an ssh error closed connection and the second time it was windows update. But now I am running it again.

**Comment by xhajnal** [comment]
It resulted with an error:
